/**
 * English intent phrase configuration (deterministic, editable).
 * Each intent: phrases (exact after normalize), requiredKeywords, optionalKeywords, negationOf.
 */

export const INTENT_PRIORITY_EN = [
  'DO_NOT_CALL',
  'NOT_INTERESTED',
  'HUMAN_AGENT',
  'CALLBACK',
  'CALLBACK_TIME',
  'BOOK_DEMO',
  'SEND_DETAILS',
  'INTERESTED',
  'ASK_PRICE',
  'ASK_COURSE',
  'ASK_DURATION',
  'ASK_LOCATION',
  'ASK_ONLINE_OFFLINE',
  'GREETING',
  'YES',
  'NO',
  'REPEAT',
  'UNKNOWN',
];

export const INTENTS_EN = {
  DO_NOT_CALL: {
    phrases: [
      'do not call me',
      'dont call me',
      "don't call me",
      'stop calling',
      'stop calling me',
      'remove my number',
      'delete my number',
      'do not contact me again',
      'dont contact me again',
      'never call me',
      'stop contacting me',
    ],
    requiredKeywords: [
      ['do', 'not', 'call'],
      ['dont', 'call'],
      ['not', 'call'],
      ['not', 'call', 'me'],
      ['not', 'call', 'again'],
      ['stop', 'calling'],
      ['remove', 'number'],
      ['delete', 'number'],
    ],
    optionalKeywords: ['again', 'never', 'contact', 'me'],
  },
  NOT_INTERESTED: {
    phrases: [
      'not interested',
      'i am not interested',
      'im not interested',
      "i'm not interested",
      'no thank you',
      'no thanks',
      'i do not want it',
      'i dont want it',
      "i don't want it",
      'not for me',
    ],
    requiredKeywords: [['not', 'interested'], ['no', 'thank'], ['dont', 'want'], ['do', 'not', 'want']],
    optionalKeywords: ['sorry'],
    negationOf: ['INTERESTED'],
  },
  HUMAN_AGENT: {
    phrases: [
      'connect me to an agent',
      'human agent',
      'i want to speak to someone',
      'transfer the call',
      'talk to your counsellor',
      'talk to a counselor',
      'speak to an agent',
      'connect to agent',
      'real person',
    ],
    requiredKeywords: [['agent'], ['counsellor'], ['counselor'], ['transfer'], ['human'], ['someone']],
    optionalKeywords: ['speak', 'talk', 'connect', 'transfer'],
  },
  CALLBACK: {
    phrases: [
      'call me later',
      'call me tomorrow',
      'i am busy now',
      'im busy now',
      'contact me later',
      'can you call again',
      'call back later',
      'please call later',
      'busy right now',
    ],
    requiredKeywords: [['call', 'later'], ['call', 'tomorrow'], ['busy'], ['call', 'again'], ['callback'], ['call', 'back']],
    optionalKeywords: ['please', 'later', 'tomorrow'],
  },
  CALLBACK_TIME: {
    phrases: [
      'six in the evening',
      'six pm',
      '6 pm',
      'tomorrow evening',
      'tomorrow morning',
      'around six',
      'call at six',
    ],
    requiredKeywords: [['evening'], ['morning'], ['afternoon'], ['pm'], ['am'], ['tomorrow'], ['today'], ['around']],
    optionalKeywords: ['six', '6', 'call', 'time'],
    stateOnly: ['waiting_for_callback_time', 'waiting_for_demo_date'],
  },
  BOOK_DEMO: {
    phrases: [
      'book a demo',
      'schedule a demo',
      'i want a demo',
      'can i attend a demo',
      'arrange a demo session',
      'demo please',
      'free demo',
    ],
    requiredKeywords: [['demo'], ['book', 'demo'], ['schedule', 'demo']],
    optionalKeywords: ['book', 'schedule', 'attend', 'arrange', 'session', 'free'],
  },
  SEND_DETAILS: {
    phrases: [
      'send details',
      'send me the details',
      'share the information',
      'whatsapp me',
      'send it on whatsapp',
      'message me the course information',
      'send the brochure',
      'share details',
      'send information',
    ],
    requiredKeywords: [['send', 'details'], ['share', 'information'], ['whatsapp'], ['send', 'brochure'], ['share', 'details'], ['send', 'information'], ['message', 'me']],
    optionalKeywords: ['course', 'details', 'whatsapp', 'brochure'],
  },
  INTERESTED: {
    phrases: [
      'i am interested',
      'yes i am interested',
      'sounds good',
      'i want to join',
      'tell me more',
      'i would like to know more',
      'interested',
      'yes interested',
    ],
    requiredKeywords: [['interested'], ['sounds', 'good'], ['want', 'join'], ['tell', 'more'], ['know', 'more']],
    optionalKeywords: ['yes', 'join', 'more'],
  },
  ASK_PRICE: {
    phrases: ['what is the fee', 'how much does it cost', 'what is the price', 'fees', 'cost'],
    requiredKeywords: [['fee'], ['fees'], ['price'], ['cost'], ['how', 'much']],
    optionalKeywords: ['course'],
  },
  ASK_COURSE: {
    phrases: ['what course', 'which course', 'tell me about the course', 'course details'],
    requiredKeywords: [['course']],
    optionalKeywords: ['what', 'which', 'about', 'details'],
  },
  ASK_DURATION: {
    phrases: ['how long is the course', 'duration', 'how many months', 'course duration'],
    requiredKeywords: [['duration'], ['how', 'long'], ['months']],
    optionalKeywords: ['course'],
  },
  ASK_LOCATION: {
    phrases: ['where is the class', 'location', 'address', 'where do you teach'],
    requiredKeywords: [['location'], ['address'], ['where']],
    optionalKeywords: ['class', 'office', 'teach'],
  },
  ASK_ONLINE_OFFLINE: {
    phrases: ['is it online', 'offline or online', 'online class', 'classroom'],
    requiredKeywords: [['online'], ['offline'], ['classroom']],
    optionalKeywords: ['or', 'class'],
  },
  GREETING: {
    phrases: ['hello', 'hi', 'good morning', 'good afternoon', 'good evening', 'namaste'],
    requiredKeywords: [['hello'], ['hi'], ['good', 'morning'], ['good', 'afternoon'], ['good', 'evening'], ['namaste']],
    optionalKeywords: [],
  },
  YES: {
    phrases: ['yes', 'yeah', 'yep', 'sure', 'okay', 'ok', 'alright'],
    requiredKeywords: [['yes'], ['yeah'], ['yep'], ['sure'], ['okay'], ['ok'], ['alright']],
    optionalKeywords: [],
  },
  NO: {
    phrases: ['no', 'nope', 'not now'],
    requiredKeywords: [['no'], ['nope'], ['not', 'now']],
    optionalKeywords: [],
  },
  REPEAT: {
    phrases: ['repeat', 'say that again', 'pardon', 'come again', 'what did you say'],
    requiredKeywords: [['repeat'], ['again'], ['pardon'], ['what', 'say']],
    optionalKeywords: ['say', 'please'],
  },
};
